"""
# Setup script for index based on Richard Sharpe's List of Identifications
"""
#--------------------------------------------------------------------------------

from django.template import Context, loader
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.core.urlresolvers import reverse
from django.utils.html import escape
from urllib import quote, unquote

#--------------------------------------------------------------------------------

editable = False
baseurl="/authortitle"
newline = '\n'

#================= Top-level functions, called directly from URL ================
#--------------------------------------------------------------------------------

# The function browse() allows browsing of the index by author/title

def browse( request, letter = 'A', pagename = 'index', called_by_editable_page = False ): #{

  # The call to 'enable edit' is just so that they can (eventually) navigate from the main site to
  # the index and then back again, without losing their 'editability' setting on the way.
  if called_by_editable_page: enable_edit()
  else: disable_edit()

  if not letter.isalpha(): letter = 'A'
  letter = letter.upper()

  # For now, just for testing, let's use a hard-coded block of HTML, generated by writeHTML.py.
  # This will need changing later.
  t = loader.get_template('authortitle/index%s.html' % letter )

  c = Context( {
      'pagename'         : pagename,
      'editable'         : editable,
      'letter'           : letter,
  } )

  return HttpResponse( t.render( c ) )

#}
# end function browse()
#--------------------------------------------------------------------------------
def browse_e( request, letter = 'A', pagename = 'index' ): #{
  return browse( request, letter, pagename, True )
#}
#--------------------------------------------------------------------------------

# The function medieval_catalogues() allows browsing of the index by medieval document

def medieval_catalogues( request, cat = '', pagename = 'cats', called_by_editable_page = False ): #{

  # The call to 'enable edit' is just so that they can (eventually) navigate from the main site to
  # the index and then back again, without losing their 'editability' setting on the way.
  if called_by_editable_page: enable_edit()
  else: disable_edit()

  if not cat.isalnum(): 
    cat = ''
  else: 
    cat = cat.upper()

  # For now, just for testing, let's use a hard-coded block of HTML, 
  # generated by cataloguesHTML.py. This will need changing later.
  if cat:
    t = loader.get_template('authortitle/catalogue%s.html' % cat )
  else:
    t = loader.get_template('authortitle/cataloguelist.html' )

  c = Context( {
      'pagename'  : pagename,
      'editable'  : editable,
      'cat'       : cat,
  } )

  return HttpResponse( t.render( c ) )

#}
# end function medieval_catalogues()
#--------------------------------------------------------------------------------
def medieval_catalogues_e( request, cat = '', pagename = 'cats' ): #{
  return medieval_catalogues( request, cat, pagename, True )
#}
#--------------------------------------------------------------------------------

# The function cat_source() allows browsing of the index by source of medieval catalogue
# e.g. B for Benedictines or B/CanterburyStAugustines for Benedictines, Canterbury-St Augustine's.

# The template name is generated from the 'document group type' e.g. B for Benedictines, then
# a hyphen, then the 'document group name', e.g. the name of the abbey etc, in lower case, and
# with all non-alphanumeric characters removed.

def cat_source( request, source = '', loc = '', pagename = 'cats', called_by_editable_page = False ): #{

  if called_by_editable_page: enable_edit()
  else: disable_edit()

  if not source.isalpha(): #{
    source = ''
    loc = ''
  #}
  else: 
    source = source.upper()

  if not loc.isalnum(): loc = ''

  full_source = source
  if loc: full_source += '-%s' % loc.lower()

  # For now, just for testing, let's use a hard-coded block of HTML, 
  # generated by cataloguesHTML.py. This will need changing later.
  t = loader.get_template('authortitle/cataloguelist%s.html' % full_source )

  c = Context( {
      'pagename'  : pagename,
      'editable'  : editable,
      'source'    : source,
      'location'  : loc,
  } )

  return HttpResponse( t.render( c ) )

#}
# end function cat_source()
#--------------------------------------------------------------------------------
def cat_source_e( request, source = '', loc = '', pagename = 'cats' ): #{
  return cat_source( request, source, loc, pagename, True )
#}
#--------------------------------------------------------------------------------
#================ End top-level functions called directly from URL ==============
#--------------------------------------------------------------------------------

## This changes links to exclude the 'editable' part of the URL  

def disable_edit(): #{

  global editable
  editable = False

  global baseurl
  baseurl = '/authortitle'
#}
#--------------------------------------------------------------------------------
## This changes links to include the 'editable' part of the URL  

def enable_edit(): #{

  global editable
  editable = True

  global baseurl
  baseurl = '/e/authortitle'
#}
#--------------------------------------------------------------------------------
